global:
  scrape_interval: 10s
  external_labels:
    monitor: 'resilience4j-poc-monitor'

scrape_configs:
  - job_name: 'spring-resilience4j-poc-monitor'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8090']
