/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.poc.resiliency;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class EmployeeManagement {
	
	public static void main(String[] args) {
		SpringApplication.run(EmployeeManagement.class, args);
	}
}
